### ISSUE TITLE
CoevenLauncher

### ISSUE THREAD

**Issue by Angel-Lizarzado** [iFeddy/CoevenLauncher#1]
Sera posible cambiar mysql por sql server? toda mi web trabaja con la misma base de datos del server en sql server >n<
Me gusta mucho este launcher, lastima no estuvo al publico mucho tiempo en Xelion Online

No domino mucho la programacion, aunque si estoy muy interesado en aprender, y me gustaria hacer lo posible por hacer funcionar este en files 2016, con sql server

Muchas gracias de antemano :D

**Comment by iFeddy** [comment]
> Sera posible cambiar mysql por sql server? toda mi web trabaja con la misma base de datos del server en sql server >n< Me gusta mucho este launcher, lastima no estuvo al publico mucho tiempo en Xelion Online
> 
> No domino mucho la programacion, aunque si estoy muy interesado en aprender, y me gustaria hacer lo posible por hacer funcionar este en files 2016, con sql server
> 
> Muchas gracias de antemano :D

Lo único que tendrías que cambiar son los endpoints para que se conecte con mssql, hoy en día ya ni es necesario que uses una db relacional para este tipo de cosas. Con que descargue un xml con la info es suficiente.
